### ISSUE TITLE
Ninebot One A1/S2 Support

### ISSUE THREAD

**Issue by ILYA2606** [fgorina/9BMetrics#6]
Ninebot One A1/S2 is not founded, because uses another Service UUID (FEE7) and characteristics:
- FEC7 (CBCharacteristicProperties.Write)
- FEC8 (CBCharacteristicProperties.Indicate)
- FEC9 (CBCharacteristicProperties.Read)

This is no problem, but no getted headers (SN, etc.).

May be have choice get all firmware data for debug?

**Comment by fgorina** [comment]
One question, what is Indicate? (I must go to BLE specification!!!)

Francisco Gorina Vanrell

+34 619 79 01 58
fgorina@gmail.com

**Comment by ILYA2606** [comment]
I added next code after found indicate characteristic:
`peripheral.readValueForCharacteristic(ch)`

And getted parsed value from characteristic:
`Printing description of buf:
▿ 13 elements
- [0] : 105
- [1] : 110
- [2] : 100
- [3] : 105
- [4] : 99
- [5] : 97
- [6] : 116
- [7] : 101
- [8] : 32
- [9] : 99
- [10] : 104
- [11] : 97
- [12] : 114`

<img width="2672" alt="2016-07-07 19 55 24" src="https://cloud.githubusercontent.com/assets/283493/16661773/9dd29fa2-4485-11e6-95d2-79c27203d16c.png">

**Comment by fgorina** [comment]
Hi

I am trying to send new version to AppStore this wekkend and will begin to scaffold the new Ninebot adapter.

Hope ir will be easy

Francisco Gorina Vanrell

+34 619 79 01 58
fgorina@gmail.com

**Comment by fgorina** [comment]
Curious. When translated to Ascii it is “indicate char”.

Francisco Gorina Vanrell

+34 619 79 01 58
fgorina@gmail.com

**Comment by fgorina** [comment]
Hi

I finished and sent the version 2.0 to AppStore. I will  egin wth the A1/S2 support.

I think the best is to create a new adapter so when detects FEE7 is launched. That way we may test everything easily.

I will talk to the nb distributor if he is interesred in giving me some access to a A1 so I may test things.

Francisco Gorina Vanrell

+34 619 79 01 58
fgorina@gmail.com

**Comment by ILYA2606** [comment]
Hello Francisco, 

Is there any progress with the support A1/S2?

**Comment by fgorina** [comment]
Hi

I have implemented some support for S1/S2 but unable to test iot for the moment.

If you download from GitHub MultiWheel branch maybe you may test it.

Also the degug function must work oK with any BLE device so may help to unravel intricacies.

Regards

Francisco Gorina Vanrell

+34 619 79 01 58
fgorina@gmail.com

**Comment by ILYA2606** [comment]
While that does not work for Ninebot One S2

![img_8028](https://cloud.githubusercontent.com/assets/283493/18777021/b44100f8-8175-11e6-9aed-51e7fc8a6a06.PNG)
![img_8029](https://cloud.githubusercontent.com/assets/283493/18777022/b44322fc-8175-11e6-8a4e-4317f8d93d7a.PNG)
![img_8030](https://cloud.githubusercontent.com/assets/283493/18777020/b41571c2-8175-11e6-8511-471fe5fe0aca.PNG)

**Comment by fgorina** [comment]
Thanks for the test, There was an error in one characteristic so it didn’t recognize the wheel.

I have pushed a modified version.

Hope it works better

Paco

+34 619 79 01 58
fgorina@gmail.com

**Comment by ILYA2606** [comment]
I getting pincode from Ninebot One S2!

Also I writing protocol on Google Drive. Check it please: 
https://docs.google.com/spreadsheets/d/1kB7Qn0dARN7p6oN5PoQ0rqPzZoc5ehP0RjSkxmk3dpU/edit?usp=sharing

**Comment by fgorina** [comment]
Hi

Good Work. Comparing with One E protocol I find following differences :

1.- Write in characteristic 6E400002-B5A3-F393-E0A9-E50E24DCCA9E instead of FFE1
2.- Subscribe to the same characteristic
3.- Change byte 3 of the messages from 0x03 to 0x11


I think the rest is the same.

After you are showing me about FEC/.

May I suggest to use the Test Mode of Gyrometrics to try to get more information?

1.- Enable Test Mode in Settings / Gyrometrics
2.-In firtst screen of Gyrometrics / Sprocket select Debug Server
3.- Select the S2 wheel

There will be in the screen the services/ characteristics of S2

You may stop recording and go back and in Gyrometrics main screen there is a new .log file that you may send to your computer.

There is more :

AFTER STEP 3

start Ninebot application and connect to NOE002

It whould function normally but all data will be recorded i the .log file. I would be very interested in one of the .log files.

Regards

Paco



Paco Gorina
E-mail : fgorina@gmail.com
Tlf.: +34 619 790 158

**Comment by fgorina** [comment]
Sorry is changing the 0x09 to 0x11



Paco Gorina
E-mail : fgorina@gmail.com
Tlf.: +34 619 790 158

On 17 abr 2017, 23:06 +0200, ILYA <notifications@github.com>, wrote:
> I getting pincode from Ninebot One S2!
> Also I writing protocol on Google Drive. Check it please:
> https://docs.google.com/spreadsheets/d/1kB7Qn0dARN7p6oN5PoQ0rqPzZoc5ehP0RjSkxmk3dpU/edit?usp=sharing
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

2016-02-04 23:10:56.841 NinebotClientTest[721:368142]  >>> Sending command 23 param 8
55aa08090117303030303030b6fe  [25: 12336, 23: 12336, 24: 12336]
55aa0409011a353171ff    [26: 12597]

2016-02-04 23:10:57.840 NinebotClientTest[721:368142]  >>> Sending command 16 param 14
55aa080901104e324f45413157fe 	[16: 12878, 17: 17743, 18: 12609]
55aa0809011335333341343595fe	[20: 16691, 21: 13620, 19: 13109]
55aa04090116313278ff			[22: 12849]

2016-02-04 23:10:58.840 NinebotClientTest[721:368142]  >>> Sending command 176 param 32

55aa080901b000000000080035ff	[176: 0, 177: 0, 178: 8]
55aa080901b300003300000007ff	[179: 0, 181: 0, 180: 51]
55aa080901b6442f0b4b01006dfe	[184: 1, 182: 12100, 183: 19211]
55aa080901b9000042002d01c4fe	[185: 0, 186: 66, 187: 301]
55aa080901bc7615080000009efe	[188: 5494, 189: 8, 190: 0]
55aa040901bf000032ff			[191: 0]

2016-02-04 23:10:59.840 NinebotClientTest[721:368142]  >>> Sending command 37 param 2
55aa040901256c055bff			[37: 1388]

2016-02-04 23:11:00.840 NinebotClientTest[721:368142]  >>> Sending command 59 param 2
55aa0409013b0000b6ff			[59: 0]

// Model works around a variable array of values.
// Each value is labeled by its position, So we have labels 0..255

// Communications work following :

	Service FFE0
	Characteristic FFE1
	Read
	Write without response
	Notify


	Client (iPhone) connects to server (Ninebot) service FFE0 and subscribes to characteristic FFE1
	
	Packets are similary built (data in Hexa)
	
//  +---+---+---+---+---+---+---+---+---+
//  |x55|xAA| l |x09|x01| c |...|ck0|ck1|
//  +---+---+---+---+---+---+---+---+---+
//
//  ... Are a UInt8 array of l-2 elements
//  ck0, ck1 are computed from the elements from l to the last of ...
//  x55 and xAA are fixed and are Beggining of buffer
//  l is the size of ... + 2 
//  x09 and x01 seem fixed for Ninebot One but it is not clear
//  c is a command or variable. 

Commands are sent from the client to the server writing the characteristic value
Answers are received by notifications of variable update

In commands c is the initial variable we ask for and there is one parmeter. It is double the number
of variables to receive.

For example for ask for variable 23 to 27 we send c = 23 and param = 8

Answers have parameters always in pairs.
c is first variable answer
each 2 bytes of parameter represent a value of the variable where v = p[i+1] * 256 + p[i]

Variable 184 and 184 combine to form a long value as : v[184]*65536+v[183]

Variable 178 is a flag variable. Bits beggining from less value are

	Bit
	0		Limit Speed
	1		Lock
	2		Beep

Other bits are unknown althought they have values

Code Error				176				0
Code Warning			177				0
Power					180				61
Work_mode				179				0
Speed					181				1
Max_Speed				191				0
Average_Speed			182				4500
Temperature				187				265
Remained_Mileage		37				1654
Ride Mileage			183 & 184Packed	83062
Single Mileage			185				0
Ride Runtime			58 o 59			O una o L'altre	
Lock					178	bit 1		8
Limit Speed				178	bit 0		8
Beep					178	bit 2		8
Drive oltage			188				54.98


Example : 

2016-02-04 23:10:55.126 NinebotClientTest[721:368142] Scanning started
2016-02-04 23:10:55.411 NinebotClientTest[721:368142] Discovered NOEPaco 001 - <__NSConcreteUUID 0x12655c550> B550AB72-A05F-7AD8-0F37-14B30C042E42
2016-02-04 23:10:55.412 NinebotClientTest[721:368142] Connecting to peripheral <CBPeripheral: 0x126720c50, identifier = B550AB72-A05F-7AD8-0F37-14B30C042E42, name = NOEPaco 001, state = disconnected>
2016-02-04 23:10:55.541 NinebotClientTest[721:368142] Connected
2016-02-04 23:10:55.542 NinebotClientTest[721:368142] Scanning stopped
2016-02-04 23:10:55.748 NinebotClientTest[721:368142] Service FFE0
2016-02-04 23:10:55.838 NinebotClientTest[721:368142] Subscrit a la variable del Ninebot : <CBCharacteristic: 0x12655cb80, UUID = FFE1, properties = 0x16, value = (null), notifying = NO>
2016-02-04 23:10:56.841 NinebotClientTest[721:368142]  >>> Sending command 23 param 8
2016-02-04 23:10:56.873 NinebotClientTest[721:368142] <<< <55aa0809 01173030 30303030 b6fe55aa 0409011a>
2016-02-04 23:10:56.874 NinebotClientTest[721:368142] <<< <353171ff>
2016-02-04 23:10:57.840 NinebotClientTest[721:368142]  >>> Sending command 16 param 14
2016-02-04 23:10:57.886 NinebotClientTest[721:368142] <<< <55aa0809 01104e32 4f454131 57fe55aa 08090113>
2016-02-04 23:10:57.886 NinebotClientTest[721:368142] <<< <35333341 343595fe 55aa0409 01163132 78ff>
2016-02-04 23:10:58.840 NinebotClientTest[721:368142]  >>> Sending command 176 param 32
2016-02-04 23:10:58.875 NinebotClientTest[721:368142] <<< <55aa0809 01b00000 00000800 35ff55aa 080901b3>
2016-02-04 23:10:58.876 NinebotClientTest[721:368142] <<< <00003300 000007ff 55aa0809 01b6442f 0b4b0100>
2016-02-04 23:10:58.898 NinebotClientTest[721:368142] <<< <6dfe55aa 080901b9 00004200 2d01c4fe 55aa0809>
2016-02-04 23:10:58.899 NinebotClientTest[721:368142] <<< <01bc7615 08000000 9efe55aa 040901bf 000032ff>
2016-02-04 23:10:59.840 NinebotClientTest[721:368142]  >>> Sending command 37 param 2
2016-02-04 23:10:59.888 NinebotClientTest[721:368142] <<< <55aa0409 01256c05 5bff>
2016-02-04 23:11:00.840 NinebotClientTest[721:368142]  >>> Sending command 59 param 2
2016-02-04 23:11:00.878 NinebotClientTest[721:368142] <<< <55aa0409 013b0000 b6ff>


Sending data

Seems similar than asking for values but the 0x09 0x01 are changed to 0x09 and 0x03

So to write the “riding mode” (variable 210, 0xd2 ) to 3 (hexa 0x0003)we shoud send

55 aa 04 09 03 d2 0300 1aff

When setting speed limit its units must be m/h. For example for setting speed (variable 116 = 0x74) limit to 7 km/h

7 km/h = 7000 m/h = 0x1B58

55 aa 04 09 03 74 581b 08ff

**Comment by fgorina** [comment]
I have analyzed a bit more your data. I built a Playground to analyze the messages and have found the following :

55 AA 0A 11 01 17 30 30 30 30 30 30 07 11 94 FE is ok
55 AA 0A 11 01 17 31 30 30 30 30 30 07 11 94 FE is incorrect
55 AA 03 11 01 22 02 C6 FF is ok
55 AA 03 11 01 28 02 C0 FF is ok
55 AA 04 11 01 22 56 00 71 FF is ok
55 AA 03 11 01 29 04 BD FF is ok
55 AA 03 11 01 1A 02 CE FF is ok
55 AA 04 11 01 1A 07 11 B7 FF is ok
55 AA 09 11 01 1A 07 11 00 00 00 00 48 6A FF is ok
55 AA 03 11 01 17 06 CD FF is ok
55 AA 08 11 01 17 35 35 35 35 35 35 90 FE is ok
55 AA 08 11 01 17 35 35 35 35 35 35 90 FE is ok

That means that the ones that don’t give you an answer are the incorrect ones (incorrect means checksum dowsn’t match)

Incidentally, pincode is just 6 bytes, the 3 other ones are the version.

As I told you it seems the protocol is the same (or nealy the same) as the ninebot One but changing one byte.

Now to understand what that means is (for the correct ones)


55 AA 0A 11 01 17 30    30 30 30 30 30 07 11   CK 94 FE -> Read data from the 23 variable 24 values (each variable 2 values)

The rest of the 30 are not used.

That's why your answer is so long. As the number of bytes to transmit are limited :two blocks are sent

55 AA 03 11 01   22 02   C6 FF -> Read 2 values from position 34. Answer is 55 AA 04 11 01 22 61 00 66 FF which means (Battery, .1 97)]

55 AA 03 11 01   28 02   C0 FF -> Read 2 values from position 40. Answer is 55 AA 04 11 01 28 00 00 C1 FF. I don't know what is 40th position :(

55 AA 04 11 01   22 56 00   71 FF -> read 86 values deom position 34. Answer is long and there should be another block. With the data you put and the info I have parsed

  (Speed, .1 0), (Voltage, .1 61.68), (Duration, .1 1537), (Battery, .1 96), (Temperature, .1 43), (AcumDistance, .1 1546338)]  (some variables are multivalue)

55 AA 03 11 01   29 04   BD FF -> Read from position 41 4 values. Answer is 55 AA 06 11 01 29 62 98 17 00 AD FE which means  [(AcumDistance, .1 1546338)]

And so on. I don't understand why it has changed the pin. From my knowledge the message shoud have been

[85, 170, 8, 17, 3, 23, 53, 53, 53, 53, 53, 53, 142, 254] in decimal

55 AA 03 11 01 17 06  CD FF  is the right command to read the PIN. means read 6 values starting position 23

55 AA 08 11 01 17 35 35 35 35 35 35 90 FE  means reqd 53 values starting at variable 23. Its answer seems not correct (probably some bytes are not ok)

Explaining a little more


55 AA   03   11   01   29   04   BD FF  -> Read acum distance

55 AA are a header
03 is the length from the variable number to the end (including checksums)
11 seems fixed and in Ninebot One is 09. That may be a protocol version number or similar
01 means read, 03 means write
29 is the variable or position in an internal array .Each position is 16 bits.  0x29 is the  Acum Distance and has 4 bytes.
05 is the length in bytes to read (in read variables) and if it is to write it would be all the data to write
BD FF is the checksum of the data

Hope it helps. To be able to support S2 in Gyrometrics is very easy but we need the services and variables because Gyrometrics uses that to select a driver. It is given by the debug option I explained in another mail.

Hope all this helps.


Paco Gorina
E-mail : fgorina@gmail.com
Tlf.: +34 619 790 158

**Comment by fgorina** [comment]
Here is a playground I used

Paco Gorina
E-mail : fgorina@gmail.com
Tlf.: +34 619 790 158

**Comment by fgorina** [comment]
Also may you try writing to FEC7 and subscribing to FEC8?

Paco Gorina
E-mail : fgorina@gmail.com
Tlf.: +34 619 790 158

**Comment by ILYA2606** [comment]
All characteristics S2 (duplicate in GyroMetrics and log):
2017 04 18_21:01:29
> c Service 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
> c     Char: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E (n)
> c     Char: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E (wx)
> c Service FEE7
> c     Char: FEC7 (w)
> c     Char: FEC9 (r)
> c     Char: FEC8 (i)
> c Service 6E400001-B5A3-F393-E0A9-E50E24DCCA9E
> c     Char: 6E400003-B5A3-F393-E0A9-E50E24DCCA9E (n)
> c     Char: 6E400002-B5A3-F393-E0A9-E50E24DCCA9E (wx)
> c Service FEE7
> c     Char: FEC7 (w)
> c     Char: FEC9 (r)
> c     Char: FEC8 (i)

**Comment by ILYA2606** [comment]
> 55 AA 04 11 01   22 56 00   71 FF -> read 86 values deom position 34. Answer is long and there should be another block. With the data you put and the info I have parsed

Its right! 
But where is speed and current?
I think next:
Battery level: 7byte in %
Battery2 level: 11byte in %
Battery average level?: 9byte in %
Temperature: 64byte * 256 + 63byte. Value in Celsius * 10
Temperature of driver.: 14byte * 256 + 13byte. Value in Celsius * 10
Voltage: 82byte * 256 + 81byte. Value in Volt * 100
Voltage2: 84byte * 256 + 83byte. Value in Volt * 100
Total Runtime: (39byte + 40byte * 256) + (41byte + 42byte * 256) * 65536. Value in seconds
Speed?: 15byte + 16byte * 256. Value in meter/hour
Current?: 19byte + 20byte * 256. Value in A * 100
Total Mileage: (21byte + 22byte * 256) + (23byte + 24byte * 256) * 65536. Value in meters
Max Speed: 17byte + 18byte * 256. Value in meter/hour

Check my updated Excel ;)

**Comment by fgorina** [comment]
Paco Gorina
E-mail : fgorina@gmail.com
Tlf.: +34 619 790 158

On 18 abr 2017, 20:39 +0200, ILYA <notifications@github.com>, wrote:
> > 55 AA 03 11 01 29 04 BD FF -> Read from position 41 4 values. Answer is 55 AA 06 11 01 29 62 98 17 00 AD FE which means [(AcumDistance, .1 1546338)]
> > Its right. How you calculate it?
> > 41 byte = 62
> > 42 byte = 98
> > It Ninebot One 16" next algorithm:
> > totalMileage = 42byte * 65536 + 41byte = 98 * 65536 + 62 = 6422590 meters = 6422km (wrong)
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.


Total Distance takes 2 variables = 4 bytes. They are variables 41 and 42.
Each variable ar 2 bytes, not one so we have :



                if let v0 = d[BLENinebot.kTotalMileage0], let v1 = d[BLENinebot.kTotalMileage1]{ // If there are the values

                    let total = Double(v1) * 65536.0 + Double(v0)
                    outarr!.append(WheelTrack.WheelValue.AcumDistance, Date(), total)
                }

But each V0 and v1 are the 2 bytes not one.

So if you get 62 98 17 00 (in hexa) -> 98 152 23 0 in dec we do:

v0 = (152 * 256) + 98 = 39010
v1 = (0 * 256) + 23 = 23

total = (23 * 65536) + 39010 = 1546338 (m) ? 1546.338 km

**Comment by fgorina** [comment]
Just a precission. What is the Service before FEC8?

I will post a new version of Ninebot drivers to the 3.0 Siri branch when got the answer. Just copy / paste the Ninebot One adapter and the Ninebot S12 Adapter  but must put the services.

As the long charecateristics seems Ninebot is now using Nordic Serial to BLE Adapter .

Regards

Paco Gorina
E-mail : fgorina@gmail.com
Tlf.: +34 619 790 158
