### ISSUE TITLE
Inmotion: Single mileage, temperature, lights, max/avg speed ?

### ISSUE THREAD

**Issue by ILYA2606** [fgorina/9BMetrics#9]
Any thoughts?

**Comment by fgorina** [comment]
ILYA which model of Inmotion?

**Comment by ILYA2606** [comment]
Inmotion V8

**Comment by fgorina** [comment]
Hi

This afternoon I am going to a Wheel meeting and will have opportunities tot est V8.

As far as I know I read
-Pitch
-Speed
-Voltage
-Distance (seems total distance but will check)
-Current
and compute battery and power.

Everything seems correct with an V5. Can you give me sggestions as what fails and how?

**Comment by palachzzz** [comment]
Hi, all. 
I've learned Inmotion protocol more detailed, 
temperature can be found in 32, and 34 byte of ex_data, and in 33 byte is always similar to 32 byte, so we can see to different temperature in inmotion V8, and maybe 3 different in others.
Also, I found this:
case DontKnow = 0x0F780101 
It is diffrent Alerts, I was able to figure out the meaning of some of them. 
For example:
0101780F20021601341A0000080201 this is Low Battery Alert (when the wheel lifts the pedals)
after IDValue goes Alert ID, so 0x20 is Battery low, after it always goes 0x02, then goes two 16-bit additional digit, in case "low battery" I don't know what in first, but second is voltage, for example there 6708 -> 67.08 volt
Also i know alert ids:
21 - speed cut-off (at  38-43 km/h), first digit -don't know, second - current speed calculated as usual 
06 - speed limit (usual 30, but when battery below 40% - it is falls), first - speed limit (int/1000) , second - current speed (usual speed calculating)
19 - fall down (Be careful alert), first -don't know, second - don't know
05 - something like "starting after idle", when you release carry button, first - starting angle, second - current speed (usual)
26 - something like "overcurrent", usual happens when you trying speed up too fast (at speed over 20), first - maybe current (int/1000), usual in range 24-26 (Amps), but I don't realy know, second - current speed (usual).

Also, I find time and date in 53-59 bytes, date is corrent but time isn't. There are RTC with battery in wheel controller, so, maybe App should correct it, but I don't know how. 

@ILYA2606 , @fgorina  I think will be great to log this in yours Apps, it may help, to understood what happened. And I trying to find JumpMaster and Cedric Hauber, to add it in android WheelLog ([this topic](http://forum.electricunicycle.org/topic/5404-wheellog-for-inmotion-development/?page=2)  ), but looks like they disappeared from April and February.

**Comment by fgorina** [comment]
Thaks you very much. I have had a hard half year with a lot of work at the office a course I am taking and a difficult situation in Catalonia so no much time to work in 9BMetrics. I think I will be a bit more free now so I would try to implement it.

Also I have now a RW GT-16 so I will experiment more with that protocol.

**Comment by fgorina** [comment]
Just a question. Do you have some values of temperature?. In a log I have 32 and 33 are 1A (26) and 34 is 20 (32) so no way to get much information about which one is each temperature. I think the higher is byte 34 so probably is the one to use. Any idea?

**Comment by palachzzz** [comment]
Hi,
I couldn't wait, and also I haven't iOS devices, so I made my own mod of WheelLog for Android :) 
https://github.com/palachzzz/WheelLogAndroid
I have many logs, and now I can say that 32 and 33 byte it is battery temperature, and 34 byte is the system temperature (probably CPU, or MEMS sensor) because it reaches 35-39 degrees quickly and stay at this values regardless of load or duration of work.
Also I found angles (tilt at 0-offset and roll at 72-byte offset), 
And also I with @ILYA2606 sniffed BT LE protocol with control commands for Inmotion, Kingsong and Gotway, and added this functionality into DarknessBot and WheelLog as well. If you interested in it, I can provide more information about it, and also you can find it in my sources as well.
Looks like inmotion adapter in wheellog - it is Java adaptation of your swift code, so I think it should be clear. But feel free to ask anything)

**Comment by fgorina** [comment]
Thanks will look at it. Probably most important temperature is 34 byte then. Will look also to the implementation of commands as I support some for Ninebot so it would be great if they also work in other wheels.

**Comment by palachzzz** [comment]
I think most important temperature is battery temp (32 or 33), because it used by official app, and it can be really different, I get 75 degree of battery temp when I did tick-tock, it is not good for battery, so it is very important to know it

**Comment by fgorina** [comment]
Yes, it is important . Most Here in Catalonia which hotter.

El dc, 27 set 2017 a les 12:58 palachzzz <notifications@github.com> va
escriure:

**Comment by fgorina** [comment]
I have added som of this things in 3.2. Someone may check it. I have no InMotion now
